# Generated by Django 3.2.8 on 2022-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
